export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: { Row: { id: string; email: string | null; display_name: string | null; created_at: string; updated_at: string }; Insert: { id: string; email?: string | null; display_name?: string | null }; Update: { email?: string | null; display_name?: string | null }; Relationships: [] }
      user_preferences: { Row: { user_id: string; theme: string; table_columns: Json; ranking_method: string; enabled_ranking_ids: Json; updated_at: string }; Insert: { user_id: string; theme?: string; table_columns?: Json; ranking_method?: string; enabled_ranking_ids?: Json }; Update: { theme?: string; table_columns?: Json; ranking_method?: string; enabled_ranking_ids?: Json }; Relationships: [] }
      draft_states: { Row: { user_id: string; draft_key: string; queue_ids: Json; keepers: Json; updated_at: string }; Insert: { user_id: string; draft_key: string; queue_ids?: Json; keepers?: Json }; Update: { queue_ids?: Json; keepers?: Json }; Relationships: [] }
      ranking_sets: { Row: { user_id: string; set_id: string; payload: Json; updated_at: string }; Insert: { user_id: string; set_id: string; payload: Json }; Update: { payload?: Json }; Relationships: [] }
      provider_connections: { Row: { user_id: string; provider: string; external_user_id: string; display_name: string | null; last_league_id: string | null; metadata: Json; updated_at: string }; Insert: { user_id: string; provider: string; external_user_id?: string; display_name?: string | null; last_league_id?: string | null; metadata?: Json }; Update: { display_name?: string | null; last_league_id?: string | null; metadata?: Json }; Relationships: [] }
      user_leagues: { Row: { user_id: string; provider: string; league_id: string; season: string; name: string; draft_id: string | null; external_user_id: string; team_name: string | null; scoring_type: string; team_count: number; last_opened_at: string; created_at: string; updated_at: string }; Insert: { user_id: string; provider: string; league_id: string; season: string; name: string; draft_id?: string | null; external_user_id?: string; team_name?: string | null; scoring_type?: string; team_count?: number; last_opened_at?: string }; Update: { name?: string; draft_id?: string | null; external_user_id?: string; team_name?: string | null; scoring_type?: string; team_count?: number; last_opened_at?: string }; Relationships: [] }
      data_artifacts: { Row: { kind: string; bucket: string; object_path: string; schema_version: number; generated_at: string; byte_size: number; metadata: Json; live_adp: Json | null }; Insert: { kind: string; bucket: string; object_path: string; schema_version: number; generated_at: string; byte_size: number; metadata?: Json; live_adp?: Json | null }; Update: { bucket?: string; object_path?: string; schema_version?: number; generated_at?: string; byte_size?: number; metadata?: Json; live_adp?: Json | null }; Relationships: [] }
      ranking_snapshots: { Row: { kind: string; schema_version: number; fetched_at: string; payload: Json; source: string; updated_at: string; live_adp: Json | null }; Insert: { kind: string; schema_version: number; fetched_at: string; payload: Json; source?: string; live_adp?: Json | null }; Update: { schema_version?: number; fetched_at?: string; payload?: Json; source?: string; live_adp?: Json | null }; Relationships: [] }
      ranking_scrape_runs: { Row: { id: string; trigger_source: string; status: string; started_at: string; finished_at: string | null; stats: Json; failures: Json; error: string | null }; Insert: { id?: string; trigger_source?: string; status?: string; started_at?: string; finished_at?: string | null; stats?: Json; failures?: Json; error?: string | null }; Update: { status?: string; finished_at?: string | null; stats?: Json; failures?: Json; error?: string | null }; Relationships: [] }
      ranking_scrape_cursors: { Row: { job_key: string; cursor: number; updated_at: string }; Insert: { job_key: string; cursor?: number }; Update: { cursor?: number }; Relationships: [] }
      intelligence_sync_runs: { Row: { id: string; trigger_source: string; status: string; started_at: string; finished_at: string | null; stats: Json; error: string | null }; Insert: { id?: string; trigger_source?: string; status?: string; started_at?: string; finished_at?: string | null; stats?: Json; error?: string | null }; Update: { status?: string; finished_at?: string | null; stats?: Json; error?: string | null }; Relationships: [] }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
